server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000

spring:
  application:
    name: weshow-rabbitmq
  profiles:
    active: dev

---
# 生产环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/weshow_account?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
      host: 192.168.11.85
      port: 7000
      password: redis
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 10 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 10
  rabbitmq:
      host: 35.154.207.19
      port: 5672
      username: test
      password: test

---
spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect